spring:
  profiles:
    group:
      "local": "local_setting,common"
      "dev": "dev_setting,common"
      "prod": "prod_setting,common"

---

# common setting
spring:
  config:
    activate:
      on-profile: "common"
mybatis:
    mapper-locations: classpath:mybatis-mapper/*.xml

---

spring:
  config.activate.on-profile: local_setting
  datasource:
    url: "jdbc:mysql://localhost:3306/bhdb"
    username: "bhuser"
    password: "bhpw"
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true

---

spring:
  config.activate.on-profile: dev_setting
  datasource:
    url: "jdbc:mysql://localhost:3306/bhdb-test"
    username: "bhuser"
    password: "bhpw"
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: false