spring:
  profiles:
    group:
      "local": "local_setting,common"
      "dev": "dev_setting,common"
      "prod": "prod_setting,common"
      "local-mariadb": "local-mariadb_setting,common"

---

# common setting
spring:
  config:
    activate:
      on-profile: "common"
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis-mapper/*.xml
    

---

spring:
  config.activate.on-profile: local_setting
  datasource:
    url: "jdbc:mysql://localhost:3306/bhdb"
    username: "bhuser"
    password: "bhpw"
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: true

---

spring:
  config.activate.on-profile: dev_setting
  datasource:
    url: "jdbc:mysql://localhost:3306/bhdb"
    username: "bhuser"
    password: "bhpw"
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    livereload:
      enabled: false

---

spring:
  config.activate.on-profile: local-mariadb_setting
  datasource:
    url: "jdbc:mariadb://localhost:3306/bhdb"
    username: "bhuser"
    password: "bhpw"
  devtools:
    livereload:
      enabled: false