spring:
  profiles:
    group:
      "local": "local_db,common"
      "dev": "dev_db,common"
      "prod": "prod_db,common"

---

# common setting
spring:
  config:
    activate:
      on-profile: "common"
mybatis:
    mapper-locations: classpath:mybatis-mapper/*.xml

---

spring:
  config.activate.on-profile: local_db
  datasource:
    url: "jdbc:mysql://localhost:3306/bhdb"
    username: "bhuser"
    password: "bhpw"
    driver-class-name: com.mysql.cj.jdbc.Driver


---

spring:
  config.activate.on-profile: dev_db
  datasource:
    url: "jdbc:mysql://localhost:3306/bhdb-test"
    username: "bhuser"
    password: "bhpw"
    driver-class-name: com.mysql.cj.jdbc.Driver